### ISSUE TITLE
plotnine issue

### ISSUE THREAD

**Issue by mertensu** [worldstrat/worldstrat#6]
Hi,

just wanted to run your exploration notebook but `plotnine` cannot be imported since it loads `matplotlib._contour` which does not exist (in version 3.6.0). 

`ModuleNotFoundError: No module named 'matplotlib._contour'`

See also here: [link](https://plotnine.readthedocs.io/en/stable/_modules/plotnine/stats/stat_density_2d.html?highlight=matplotlib._contour)

If I did anything wrong with the setup, please let me know. 

Thanks in advance!

**Comment by jucor** [comment]
Thanks for flagging this @mertensu ! 
Uh oh, looks like this follows from a breaking change in matplotlib 3.6.0, also released 2 days ago.  There is an active issue in plotnine, opened 2 days ago: https://github.com/has2k1/plotnine/issues/619

@ivanorsolic , could you please pin the plotnine and maltplotlib versions in `environment.yml` to pre-break versions until this is fixed? Generally for reproducibility it would be a good idea to pin all versions while we're at it :)

**Comment by mertensu** [comment]
See https://github.com/worldstrat/worldstrat/pull/7

**Comment by jucor** [comment]
Thanks @mertensu ! Closing as fixed by #7 .
